In [2]:
import tensorflow as tf 
import tensorflow.keras as keras #type:ignore
import  numpy as np

print(tf. __version__)
print(tf.config.list_physical_devices('GPU'))

2.10.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
#  creating a variable

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [9]:
changeable_tensor[0].assign(7)  #type:ignore
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>


In [10]:

# unchangeable_tensor[0].assign(7)

In [11]:
# random tensors 


random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
print(random_1)
print(random_2)
print(random_2 == random_1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


In [12]:
# shuffling a tensor

not_shuffled_tensor = tf.constant([[10,7]
                                   ,[7,10],
                                   [5,2],])


shuffled_tensor = tf.random.shuffle(not_shuffled_tensor)
print(shuffled_tensor)

tf.Tensor(
[[ 7 10]
 [10  7]
 [ 5  2]], shape=(3, 2), dtype=int32)


In [13]:
print('😊😪🤣🔥🖋️📜👌😒😍😂❤️🖥️')

😊😪🤣🔥🖋️📜👌😒😍😂❤️🖥️


In [14]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [16]:
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [17]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [18]:
rank_2 = tf.constant([[2,6],
                      [9,0]])

rank_2.ndim,rank_2.shape

(2, TensorShape([2, 2]))

In [19]:
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 0])>

In [20]:
# adding extra dimension 

rank_3 = rank_2[...,tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [6]],

       [[9],
        [0]]])>

In [21]:
rank_3.ndim

3

In [22]:
# alternative

tf.expand_dims(rank_2 , axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [6]],

       [[9],
        [0]]])>

In [23]:
tf.expand_dims(rank_2,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 6],
        [9, 0]]])>

In [24]:
# manipluating tensors

tensor = tf.constant([[10,7],[3,4]])
tensor + 10
# here original tensors value doesnt change

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [25]:
print(tensor * 10 )
print(tensor - 10)
print(tensor / 10)  



tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


In [26]:
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [27]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [28]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [29]:
tensor_3 = tf.constant([
    [1,2,5],
    [7,2,1],
    [3,3,3],
    ])
tensor_2 = tf.constant([
    [3,5],
    [6,7],
    [1,8],
    ])

mul_tensor = tf.matmul(tensor_3, tensor_2)
print(mul_tensor)

tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)


In [30]:
tensor_x = tf.constant([
    [3,5],
    [6,7],
    [1,8],
    ])
tensor_y = tf.constant([
    [3,5],
    [6,7],
    [1,8],
    ])

tensor_yr = tf.reshape(tensor_y,shape=(2,3))
print(tensor_x.shape)
print(tensor_yr.shape)


tf.matmul(tensor_x, tensor_yr)

(3, 2)
(2, 3)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]])>

In [31]:
tensor_x = tf.constant([
    [3,5],
    [6,7],
    [1,8],
    ])
tensor_y = tf.constant([
    [3,5],
    [6,7],
    [1,8],
    ])

tf.matmul(tensor_x, tf.transpose(tensor_y)) 


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]])>

In [32]:
tensor_x = tf.constant([
    [3,5],
    [6,7],
    [1,8],
    ])
tensor_y = tf.constant([
    [3,5],
    [6,7],
    [1,8],
    ])

tf.tensordot(tensor_x, tf.transpose(tensor_y),axes=1)  #

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]])>

In [33]:
d = tf.constant([-7,-10])
d
   

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [34]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [35]:
E = tf.constant(np.random.randint(0,100,size =50))

In [36]:
tf.size(E), E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [37]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [38]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [39]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [40]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2455>

In [41]:
tf.reduce_prod(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [42]:

from numpy import float32


Ef = tf.cast(E , dtype=float32)
tf.math.reduce_std(Ef ), tf.math.reduce_variance(Ef)

(<tf.Tensor: shape=(), dtype=float32, numpy=27.833971>,
 <tf.Tensor: shape=(), dtype=float32, numpy=774.73>)

In [44]:
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [45]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [54]:
b =F[tf.argmax(F)]

In [51]:
a =  tf.reduce_max(F)

In [52]:
a ==b

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [53]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [55]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [56]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [58]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [59]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [64]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed

(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

In [68]:
# one hot encoding 
some_list = [0,1,2,3] 


tf.one_hot(some_list , depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [69]:
tf.one_hot(some_list,depth=4 , on_value='yo i love deep learning',off_value='i love gaming ')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'i love gaming ', b'i love gaming ',
        b'i love gaming '],
       [b'i love gaming ', b'yo i love deep learning', b'i love gaming ',
        b'i love gaming '],
       [b'i love gaming ', b'i love gaming ', b'yo i love deep learning',
        b'i love gaming '],
       [b'i love gaming ', b'i love gaming ', b'i love gaming ',
        b'yo i love deep learning']], dtype=object)>

In [70]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [72]:
tf.math.sqrt(tf.cast(H,dtype=float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [73]:
H_f = tf.cast(H , dtype=float32)
tf.math.log(H_f)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.6094378, 1.7917594,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [82]:
#  tensors and numpy 

J = tf.constant(np.array([3,4,6]))
J

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 6])>

In [81]:
np.array(J) ,type(np.array(J))

(array([3, 4, 6]), numpy.ndarray)

In [84]:
numpy_j = tf.constant(np.array([3.,7.,9.]))
tensor_J = tf.constant([3.,7.,9.])

numpy_j.dtype , tensor_J.dtype

(tf.float64, tf.float32)

In [86]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]